### PR TITLE
Add json marshalling functions to every message

### PR DESCRIPTION
**Pull request by elb3k**
golang `encoding/json` is used by many gophers, but it does not support all of the `proto.Message` features.

But one can add custom marshal/marshaling functions for the specific types. And since `protojson.Marshal` and `protojson.Unmarshal` supports all of the `proto.Message` features. Adding simple wrapper function allows `encoding/json` to `protojson` encode/decoder.

So I added `genJSONFunctions` which adds simple wrappers.

### CODE REVIEW

**Comment by puellanivis** [comment]
https://github.com/protocolbuffers/protobuf-go/blob/master/CONTRIBUTING.md

**Comment by elb3k** [comment]
> > At this time, we are unfortunately unable to accept GitHub pull requests.
> 
> https://github.com/protocolbuffers/protobuf-go/blob/master/CONTRIBUTING.md

Got it! Will create Gerit request.

**Comment by elb3k** [comment]
But the question is why github PRs are not supported, gerrit workflow has so much friction.

**Comment by puellanivis** [comment]
From `CONTRIBUTING.md`:
> The source of truth for this repository is at go.googlesource.com/protobuf.

We cannot take github PRs because the code here is just a copy of the source of truth, and so changes to it will not be reflected properly everywhere it need be.

**Pull request closed without merging**
